apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
    prometheus.yml: |
      global:
        scrape_interval: 10s
        evaluation_interval: 10s

      scrape_configs:
        # - job_name: 'otel-collector'
        #   static_configs:
        #     - targets: [ 'simplest-collector:8889' ]
        - job_name: 'kube-state-metrics'
          static_configs:
            - targets: [ 'ksm-kube-state-metrics:8080' ]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceName: prometheus
  replicas: 1
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  selector:
    matchLabels:
      db: prometheus
  template:
    metadata:
      labels:
        db: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.0.1
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 8889
              name: remote-write
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention.time=1h'
            - '--web.enable-remote-write-receiver' # This is necessary to k6 to send metrics to Prometheus
            - '--enable-feature=native-histograms'
            - '--web.enable-otlp-receiver'
          volumeMounts:
              - mountPath: /etc/prometheus
                name: prometheus-config
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  selector:
    db: prometheus
  clusterIP: None
  ports:
    - port: 9090
      name: http
    - port: 8889
      name: remote-write
