apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring
data:
    tempo.yml: |
      server:
        http_listen_port: 3200
      distributor:
        receivers:
          otlp:
            protocols:
              grpc:
              http:
      storage:
        trace:
          backend: local                     # backend configuration to use
          wal:
            path: /var/tempo/wal            # where to store the the wal locally
          local:
            path: /var/tempo/traces
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
  namespace: monitoring
spec:
  serviceName: tempo
  replicas: 1
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  selector:
    matchLabels:
      db: tempo
  template:
    metadata:
      labels:
        db: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          ports:
            - containerPort: 3200
              name: http
            - containerPort: 4317
              name: otlp-grpc
          args:
            - "-config.file=/conf/tempo.yml"
          volumeMounts:
              - mountPath: /conf/
                name: tempo-config
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: monitoring
spec:
  selector:
    db: tempo
  clusterIP: None
  ports:
    - port: 3200
      name: http
    - port: 4317
      name: otlp-grpc
