apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: simplest
  namespace: monitoring
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
      attributes:
        actions:
          - key: loki.resource.labels
            action: insert
            value: service_name, environment
      resource:
        attributes:
          - key: environment
            from_attribute: environment
            action: insert
          # rename the service.name attribute to service_name
          - key: service_name
            from_attribute: service.name
            action: insert

    exporters:
      debug:
        verbosity: detailed
      # https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter
      # https://grafana.com/docs/loki/latest/reference/loki-http-api/

      #    OTLP/HTTP exporter option 1
      # otlphttp:
      #   logs_endpoint: http://loki:3100/otlp/v1/logs
      #   metrics_endpoint: http://prometheus:9090/api/v1/otlp/v1/metrics
      #   tls:
      #     insecure: true

      #    OTLP/HTTP exporter option 2
      otlphttp/prometheus: # '/prometheus' is my custom name for this exporter
        endpoint: http://prometheus:9090/api/v1/otlp
        tls:
          insecure: true
      otlphttp/loki: # '/logs' is my custom name for this exporter
        endpoint: http://loki:3100/otlp
        tls:
          insecure: true

      otlp/my-tempo:
        endpoint: tempo:4317
        tls:
          insecure: true

      otlp/oteltui:
        endpoint: otel-tui:4317
        tls:
          insecure: true

      otlp/jaeger:
        endpoint: jaeger:4317
        tls:
          insecure: true

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [resource, attributes, batch]
          exporters: [debug, otlphttp/loki, otlp/oteltui]
        metrics:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [debug, otlphttp/prometheus, otlp/oteltui]
        traces:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [debug, otlp/my-tempo, otlp/oteltui, otlp/jaeger]
