apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-instrumentation
  namespace: disecomm-apps
spec:
  exporter:
    endpoint: http://simplest-collector.monitoring:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
#  java:
#    env:
#      - name: OTEL_EXPORTER_OTLP_ENDPOINT
#        value: http://simplest-collector:4318
