apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: disecomm-apps
spec:
  selector: # pods that this deployment will manage
    matchLabels:
      app: api-gateway
  template:
    metadata:
      name: api-gateway # the name of the pod itself
      labels: # labels of the pods, this must match the selector above
        app: api-gateway
    spec:
      containers:
        - name: app # name of the container inside the pod
          image: k3d-myregistry.localhost:5001/disecomm-api-gateway:local
          imagePullPolicy: Always # always pull the image from the registry
          ports:
            - containerPort: 5102 # the port the container listens on
              name: http # the name of the port
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: HTTP_SERVER_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  namespace: disecomm-apps
spec:
  selector: # the pods that this service will route traffic to
    # selector must match the labels of the pods, it uses include all the labels
    app: api-gateway
  ports:
    - protocol: TCP # the protocol that the service should use, the default is TCP
      port: 8080 # the port the clients will connect to
      targetPort: 8080  # the port the pods are listening on, must match the containerPort
      name: http # the name of the port
  type: ClusterIP


