apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
  namespace: disecomm-apps
spec:
  replicas: 1
  selector: # pods that this deployment will manage
    matchLabels:
      app: product-catalog
  template:
    metadata:
      name: product-catalog # the name of the pod itself
      labels: # labels of the pods, this must match the selector above
        app: product-catalog
      annotations:
        instrumentation.opentelemetry.io/inject-java: "java-instrumentation"
    spec:
      containers:
        - name: app # name of the container inside the pod
          image: myregistry.localhost:5001/disecomm-product-catalog:local
          imagePullPolicy: Always # always pull the image from the registry
          ports:
            - containerPort: 5102 # the port the container listens on
              name: grpc # the name of the port
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: GRPC_SERVER_PORT
              value: "5102"
          resources:
            limits:
              memory: "512Mi"
              cpu: "2000m" # means 500 millicores, or 0.5 cores
            requests:
              memory: "512Mi"
              cpu: "500m" # means 100 millicores, or 0.1 cores
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-svc
  namespace: disecomm-apps
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
spec:
  selector: # the pods that this service will route traffic to
    # selector must match the labels of the pods, it uses include all the labels
    app: product-catalog
  ports:
    - protocol: TCP # the protocol that the service should use, the default is TCP
      port: 5102 # the port the clients will connect to
      targetPort: 5102  # the port the pods are listening on, must match the containerPort
      name: grpc # the name of the port
  type: ClusterIP


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-catalog-hpa
  namespace: disecomm-apps
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-catalog
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30 # how long to wait before scaling down
      policies:
        - type: Pods
          value: 1 # the number of pods to keep
          periodSeconds: 30 # how long to wait before removing pods
    scaleUp:
      stabilizationWindowSeconds: 0 # how long to wait before scaling up
      policies:
        - type: Pods
          value: 1 # the number of pods to add each time
          periodSeconds: 30 # how long to wait before adding more pods

