FROM openjdk:21-jdk-slim AS builder

RUN echo "📦 Compile common dependencies"
WORKDIR /dependencies

# Protobuf common dependencies
# for caching purposes, we copy the pom.xml, mvnw and .mvn files first
COPY ./protobuf/pom.xml ./protobuf/mvnw ./protobuf/
COPY ./protobuf/.mvn ./protobuf/.mvn
RUN cd protobuf && ./mvnw dependency:go-offline -B
# then we copy the source code and build the project
COPY ./protobuf/src ./protobuf/src
RUN cd protobuf && ./mvnw clean install -DskipTests

# Make .jar files available to the main build stage
RUN mv /root/.m2/repository/io/giovannymassuia/disecomm/ /dependencies/maven

FROM scratch AS dependencies

# Making dependencies available to the main build stage
COPY --from=builder /dependencies/maven /dependencies/maven
