apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: monitoring
spec:
  serviceName: loki
  replicas: 1
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  selector:
    matchLabels:
      db: loki
  template:
    metadata:
      labels:
        db: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
          ports:
            - containerPort: 3100
          env:
            - name: LOKI_LIMITS_CONFIG_RETENTION_PERIOD
              value: "1h"
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  selector:
    db: loki
  clusterIP: None
  ports:
    - port: 3100
      name: http
